#!/usr/bin/env bash
# Configures an ubuntu machine with nginx and a root file
apt-get -y update
apt-get -y install nginx
echo "Hello world!" > /var/nginx/www/index.nginx-debian.html
service nginx start
