#!/usr/bin/env bash
# Configures an ubuntu machine with nginx and a root file
apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
service nginx start
