#!/usr/bin/env bash
# Script installs and configures nginx then redirects /redirect_me
sudo apt-get -y update
sudo apt-get -y install nginx
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
sudo sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://www.github.com/ permanent;' /etc/nginx/sites-available/default
service nginx restart
