#!/usr/bin/env bash
# Configures an Ubuntu machine with Nginx
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo service nginx start
sudo echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
sudo sed -i '/http {/a \\tadd_header X-Served-By $hostname;' /etc/nginx/nginx.conf
sudo service nginx restart
