#!/usr/bin/env bash
# installs, configures, and starts the load balancer
apt-get -y install --no-install-recommends software-properties-common
add-apt-repository ppa:vbernat/haproxy-2.0
apt-get update
apt-get -y install haproxy=2.0.\*

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy stop
# configure proxy to send traffic to web-01 web-02
# distribute requests using roundrobin
conf=\
"
# hbnb back end
backend hbnb-backend
    mode http
    balance roundrobin
    no option http-use-htx
    server 134113-web-01 3.84.239.19:80 check
    server 134113-web-02 18.210.33.168:80 check

# hbnb front end
frontend hbnb-frontend
    bind *:80
    mode http
    no option http-use-htx
    default_backend hbnb-backend
"
echo "$conf" | sudo tee -a "/etc/haproxy/haproxy.cfg"
sudo service haproxy start
