#!/usr/bin/env bash
# Configures nginx to listen to port 80
sudo sed -i 's/8080 default_server/80 default_server/g' /etc/nginx/sites-available/default
sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
