#!/usr/bin/env bash
# Configures nginx to listen to port 80
rm /etc/nginx/sites-enabled/default
sed -i 's/listen 8080 default_server;/listen 80 default_server;/' /etc/nginx/sites-available/default
sed -i 's/listen [::]:8080 default_server ipv6only=on;/listen [::]:80 default_server;/' /etc/nginx/sites-available/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
