#!/usr/bin/env bash
# manages 'manage_my_process' file

p_path=${PWD}/manage_my_process
f_path=/var/run/my_process.pid


if [ $# -ne 1 ]; then
    echo "Usage: manage_my_process {start|stop|restart}"
else
    case "$1" in
        "start")
            bash "$p_path" &
            echo "$!" > "$f_path"
            echo "manage_my_process started"
            ;;
        "stop")
            pkill -f "$p_path"
            rm "$f_path"
            echo "manage_my_process stopped"
            ;;
        "restart")
            pkill -f "$p_path"
            rm "$f_path"
            bash "$p_path" &
            echo "$!" > "$f_path"
            echo "manage_my_process started"
            ;;
    esac
fi