#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
msg=""
i=1
while [ $i -le 10 ]; do
    if [ $i -eq 9 ]; then
        msg="Best School\nHi"
    else
        msg="Best School"
    fi

    echo -e "$msg"
    i=$((i+1))
done
    