#!/usr/bin/env bash
# Script that displays number from 1 to 20
msg=""
i=1
while [ $i -le 20 ]; do
    case $i in
        4)    
            msg="$i\nbad luck from China"
            ;;
        9)
            msg="$i\nbad luck from Japan"
            ;;
        17)
            msg="$i\nbad luck from Italy"
            ;;
        *)
            msg="$i"
            ;;
        esac
    echo -e "$msg"
    i=$((i+1))
done