#!/usr/bin/env bash
# Script displays the time for 12 hours and 59 min
hr=0
while [ $hr -lt 12 ]; do
    echo "Hour: $hr"
    min=1
    while [ $min -lt 60 ]; do
        echo "$min"
        min=$((min+1))
    done
    hr=$((hr+1))
done