#!/usr/bin/env bash
# sets nginx to run as user nginx & listen on 8080
pkill -f apache2
sed -i "s/80/8080/g" /etc/nginx/sites-enabled/default
chmod 644 /etc/nginx/nginx.conf
chown nginx:nginx /etc/nginx/nginx.conf
sudo -u nginx service nginx start
